### ISSUE TITLE
Begin developing the agent for Challenge 1 (Control)

### ISSUE THREAD

**Issue by PedroMaia21** [GustavoReggio/RMI#1]
Develop the first agent focusing on controlling the robot using the obstacle sensors and motors.

**Comment by GustavoReggio** [comment]
OK, Vou focar nisto, só alterei o README para ver se os commits estãoa afuncionar, pois estou com dificuldades de fazer pull

**Comment by GustavoReggio** [comment]
Nao acho no doc fornecido pelo prof, mas o robô só pode virar para esqueda ???
